inactivity/urls.py
from django.urls import path

from . import views

app_name = "inactivity"

urlpatterns = [
    path("", views.index, name="index"),
    path("manage", views.manage, name="manage_requests"),
    path("loa_requests", views.list_loa_requests, name="list_loa_requests"),
    path(
        "loa_requests/pending",
        views.list_pending_loa_requests,
        name="list_pending_loa_requests",
    ),
    path("loa_requests/create", views.create_loa_request, name="create_loa_request"),
    path(
        "loa_requests/<int:request_id>/cancel",
        views.cancel_loa_request,
        name="cancel_loa_request",
    ),
    path(
        "loa_requests/<int:request_id>/approve",
        views.approve_loa_request,
        name="approve_loa_request",
    ),
    path(
        "loa_requests/<int:request_id>",
        views.view_loa_request,
        name="view_loa_request",
    ),
]

inactivity/models.py
import dhooks_lite
from multiselectfield import MultiSelectField

from django.contrib.auth.models import Group, User
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

from allianceauth.authentication.models import State


class General(models.Model):
    """Meta model for app permissions"""

    class Meta:
        managed = False
        default_permissions = ()
        permissions = (
            ("basic_access", "Can access this app"),
            ("manage_leave", "Can manage leave of absence requests"),
        )


class InactivityPingConfig(models.Model):
    name = models.CharField(
        max_length=48,
        unique=True,
        help_text=_("Internal name for the inactivity policy. Must be unique."),
    )
    days = models.PositiveIntegerField(
        help_text=_("The number of days the user must be inactive.")
    )
    text = models.TextField(
        help_text=_("The text of the message or notification sent to the end user.")
    )

    groups = models.ManyToManyField(
        Group,
        blank=True,
        help_text=_(
            "Groups subject to the inactivity policy. If empty, applies to all groups."
        ),
        related_name="+",
    )

    states = models.ManyToManyField(
        State,
        blank=True,
        help_text=_(
            "States subject to the inactivity policy. If empty, applies to all states."
        ),
        related_name="+",
    )

    class Meta:
        default_permissions = ()
        verbose_name = "inactivity policy"
        verbose_name_plural = "inactivity policies"

    def __str__(self):
        return _("inactivity policy: %(name)s") % {"name": self.name}

    def is_applicable_to(self, user: User) -> bool:
        is_applicable = True
        if self.groups.count() > 0:
            is_applicable &= self.groups.filter(user=user).count() > 0
        if self.states.count() > 0:
            is_applicable &= self.states.filter(userprofile=user.profile).count() > 0
        return is_applicable


class InactivityPing(models.Model):
    config = models.ForeignKey(InactivityPingConfig, on_delete=models.CASCADE)
    timestamp = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        default_permissions = ()

    def __str__(self):
        return _("ping [policy='%(config_name)s' user='%(user_name)s']") % {
            "config_name": self.config.name,
            "user_name": self.user.profile.main_character.character_name,
        }


class LeaveOfAbsence(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    approver = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+"
    )
    start = models.DateField(help_text=_("The start of the leave of absence."))
    end = models.DateField(
        blank=True,
        null=True,
        help_text=_(
            "The end of the leave of absence. Leave blank for an indefinite leave."
        ),
    )
    notes = models.TextField(blank=True)

    class Meta:
        default_permissions = ()

    def save(self, *args, **kwargs):
        orig = LeaveOfAbsence.objects.filter(pk=self.pk).first()
        # find possible configs that could apply to the user, then alert based on that
        configs = []
        for config in InactivityPingConfig.objects.all():
            if config.is_applicable_to(self.user):
                configs.append(config)
        webhooks = Webhook.objects.filter(
            Q(ping_configs__in=configs) | Q(ping_configs=None), Q(is_active=True)
        )
        if self._state.adding:

            for webhook in webhooks:
                if str(Webhook.NOTIFICATION_TYPE_LOA_NEW) in webhook.notification_types:
                    if webhook.webhook_type == Webhook.WEBHOOK_TYPE_DISCORD:
                        hook = dhooks_lite.Webhook(webhook.url)
                        hook.execute(
                            "**%(user_name)s** has submitted a new leave of absence from **%(start)s** to **%(end)s**"
                            % {
                                "user_name": self.user.profile.main_character.character_name,
                                "start": self.start,
                                "end": self.end if self.end else "—",
                            }
                        )
        elif self.approver and not orig.approver:
            for webhook in webhooks:
                if (
                    str(Webhook.NOTIFICATION_TYPE_LOA_APPROVED)
                    in webhook.notification_types
                ):
                    if webhook.webhook_type == Webhook.WEBHOOK_TYPE_DISCORD:
                        hook = dhooks_lite.Webhook(webhook.url)
                        hook.execute(
                            "**%(user_name)s**'s leave of absence from **%(start)s** to **%(end)s** has been approved by **%(approver_name)s**"
                            % {
                                "user_name": self.user.profile.main_character.character_name,
                                "approver_name": self.approver.profile.main_character.character_name,
                                "start": self.start,
                                "end": self.end if self.end else "—",
                            }
                        )

        super(LeaveOfAbsence, self).save(*args, **kwargs)

    def __str__(self):
        return _("%(user_name)s's leave starting %(start)s") % {
            "start": self.start,
            "user_name": self.user.profile.main_character.character_name,
        }

    def clean(self):
        if self.end and self.end < self.start:
            raise ValidationError(_("End date must be after start date."))


class Webhook(models.Model):
    NOTIFICATION_TYPE_INACTIVE_USER = 1
    NOTIFICATION_TYPE_LOA_NEW = 10
    NOTIFICATION_TYPE_LOA_APPROVED = 11

    NOTIFICATION_TYPE_CHOICES = [
        (NOTIFICATION_TYPE_INACTIVE_USER, "Inactive User"),
        (NOTIFICATION_TYPE_LOA_NEW, "Leave of Absence - Created"),
        (NOTIFICATION_TYPE_LOA_APPROVED, "Leave of Absence - Approved"),
    ]

    WEBHOOK_TYPE_DISCORD = 1

    WEBHOOK_TYPE_CHOICES = [
        (WEBHOOK_TYPE_DISCORD, _("Discord Webhook")),
    ]

    name = models.CharField(
        max_length=64, unique=True, help_text="short name to identify this webhook"
    )

    notification_types = MultiSelectField(
        choices=NOTIFICATION_TYPE_CHOICES,
        help_text=("only notifications of the selected types are sent to this webhook"),
    )

    ping_configs = models.ManyToManyField(
        InactivityPingConfig,
        blank=True,
        help_text="The inactivity policies to alert for. If left blank, all policies are alerted for.",
    )

    url = models.CharField(
        max_length=255,
        unique=True,
        help_text=(
            "URL of this webhook, e.g. "
            "https://discordapp.com/api/webhooks/123456/abcdef"
        ),
    )
    webhook_type = models.IntegerField(
        choices=WEBHOOK_TYPE_CHOICES,
        default=WEBHOOK_TYPE_DISCORD,
        help_text="type of this webhook",
    )
    is_active = models.BooleanField(
        default=True,
        help_text="whether notifications are currently sent to this webhook",
    )

inactivity/templates/inactivity/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}

{% block page_title %}{% translate "Leave of Absence Management" %}{% endblock %}

{% block content %}
    <div class="aa-inactivity">
        <h1 class="page-header text-center">{% translate "Leave of Absence Management" %}</h1>

        {% block details %}{% endblock %}
    </div>
{% endblock %}

inactivity/templates/inactivity/create_loa.html
{% extends 'inactivity/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}
{% load bootstrap %}
{% block details %}

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">{% translate "Create Request" %}</h3>
        </div>
        <div class="panel-body" style="min-height: 100px;">
            <form role="form" method="POST" action="{% url 'inactivity:create_loa_request' %}">
                {% csrf_token %}
                {{ create_form|bootstrap }}
                <div class="form-group">
                    <div class="pull-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

{% block extra_javascript %}
{% include 'bundles/datatables-js.html' %}
<script type="application/javascript">

    let loaSettings = {
        listRequestsUrl: '{% url "inactivity:list_loa_requests" %}',
        approveRequestUrl:'{% url "inactivity:approve_loa_request" request_id=12345 %}',
        cancelRequestUrl:'{% url "inactivity:cancel_loa_request" request_id=12345 %}',
        csrfToken: '{% csrf_token %}',
    };

</script>
<script type="application/javascript" src="{% static 'inactivity/js/loa_request_list.js' %}" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==" crossorigin="anonymous"></script>

  <script>
  $( function() {
    $( "#id_start" ).datepicker();
    $( "#id_end" ).datepicker();
  } );
  </script>
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"  type="text/css">
{% endblock %}

{% block extra_script %}
{% endblock %}

inactivity/templates/inactivity/index.html
{% extends 'inactivity/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">{% translate "Current Requests" %}</h3>
        </div>
        <div class="panel-body" style="min-height: 100px;">
            <div class="pull-right">

                {% if perms.inactivity.manage_leave %}
                    <a class="btn btn-primary" href="{% url 'inactivity:manage_requests' %}">{% translate "Manage Requests" %}</a>
                {% endif %}
                <a class="btn btn-success" href="{% url 'inactivity:create_loa_request' %}">{% translate "Create Request" %}</a>
            </div>
            <table id="table-requests" style="width: 100%;" class="table table-striped">
                <thead>
                    <tr>
                        <th>{% translate "Start" %}</th>
                        <th>{% translate "End" %}</th>
                        <th>{% translate "Approved" %}</th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>

{% endblock %}

{% block extra_javascript %}
{% include 'bundles/datatables-js.html' %}
<script type="application/javascript">

    let loaSettings = {
        listRequestsUrl: '{% url "inactivity:list_loa_requests" %}',
        listPendingRequestsUrl: '{% url "inactivity:list_loa_requests" %}',
        approveRequestUrl:'{% url "inactivity:approve_loa_request" request_id=12345 %}',
        cancelRequestUrl:'{% url "inactivity:cancel_loa_request" request_id=12345 %}',
        csrfToken: '{% csrf_token %}',
    };

</script>
<script type="application/javascript" src="{% static 'inactivity/js/loa_request_list.js' %}" ></script>
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'inactivity/css/aa-bootstrap-fix.min.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'inactivity/css/inactivity.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}
{% endblock %}

inactivity/templates/inactivity/manage.html
{% extends 'inactivity/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">{% translate "Pending Requests" %}</h3>
        </div>
        <div class="panel-body" style="min-height: 100px;">
            <table id="table-requests" style="width: 100%;" class="table table-striped">
                <thead>
                    <tr>
                        <th>{% translate "User" %}</th>
                        <th>{% translate "Start" %}</th>
                        <th>{% translate "End" %}</th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
    {% include 'inactivity/modals/modal_dialog.html' with name="ViewRequest" %}

{% endblock %}

{% block extra_javascript %}
{% include 'bundles/datatables-js.html' %}
<script type="application/javascript">

    let loaSettings = {
        listRequestsUrl: '{% url "inactivity:list_loa_requests" %}',
        listPendingRequestsUrl: '{% url "inactivity:list_pending_loa_requests" %}',
        viewRequestModalUrl: '{% url "inactivity:view_loa_request" request_id=12345 %}',
        approveRequestUrl:'{% url "inactivity:approve_loa_request" request_id=12345 %}',
        cancelRequestUrl:'{% url "inactivity:cancel_loa_request" request_id=12345 %}',
        csrfToken: '{% csrf_token %}',
    };

</script>
<script type="application/javascript" src="{% static 'inactivity/js/pending_loa_request_list.js' %}" ></script>
<script>

    $('#modalViewRequestContainer').on('show.bs.modal', function(event) {
            var button = $(event.relatedTarget)
            var ajax_url = button.data('ajax_url');
            $("#modalViewRequestContent").load(ajax_url)
        });

</script>
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'inactivity/css/aa-bootstrap-fix.min.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'inactivity/css/inactivity.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}
{% endblock %}